language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

matrix:
  allow_failures:
    - go: tip

sudo: false

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sudo apt-get update && sudo apt-get install -y libsecret-1-0;
    fi

install:
  - TRAVIS_NODE_VERSION="6";
      # Clear out whatever version of NVM Travis has as it is old.
  - rm -rf ~/.nvm;
      # Grab NVM.
  - git clone https://github.com/creationix/nvm.git ~/.nvm;
      # Checkout the latest stable tag.
      # Note that you can just hardcode a preferred version here.
  - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`);
      # Install the desired version of Node
  -  source ~/.nvm/nvm.sh;
  -  nvm install $TRAVIS_NODE_VERSION;
  - npm install
  - npm run vscode:prepublish
  - if [[ "$(go version)" =~ "go version go1.8" ]]; then go get -u -v github.com/nsf/gocode; else go get -u -v github.com/mdempsky/gocode; fi
  - go get -u -v github.com/rogpeppe/godef
  - if [[ "$(go version)" =~ "go version go1.8" ]]; then echo skipping gogetdoc; else go get -u -v github.com/zmb3/gogetdoc; fi
  - if [[ "$(go version)" =~ "go version go1.8" ]]; then echo skipping golint; else go get -u -v golang.org/x/lint/golint; fi
  - go get -u -v github.com/ramya-rao-a/go-outline
  - go get -u -v github.com/sqs/goreturns
  - go get -u -v golang.org/x/tools/cmd/gorename
  - go get -u -v github.com/uudashr/gopkgs/cmd/gopkgs
  - go get -u -v github.com/acroca/go-symbols
  - go get -u -v github.com/cweill/gotests/...
  - go get -u -v github.com/haya14busa/goplay/cmd/goplay
  - go get -u -v github.com/davidrjenni/reftools/cmd/fillstruct
  - go get -u -v github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - npm run lint
  - npm test --silent
